### ISSUE TITLE
'bar' compile error

### ISSUE THREAD

**Issue by mg1075** [esripdx/angular-dimple#57]
I do not know if others are having this error as of this moment, 
but I was getting an angular compile error saying 'bar' was missing a required controller called 'progress'. 

The problem did not go away until I renamed 'bar' in the directive to 'barchart' to avoid whatever naming collision was taking place.

**Comment by paulcpederson** [comment]
If you ware using a different directive with a `bar` element in it (probably a loading bar?) then there will be a collision, your solution is the best way to get around that I think!
