### ISSUE TITLE
Bar and Area graphs seem to always render as Stacked Graphs?

### ISSUE THREAD

**Issue by gmsharpe** [esripdx/angular-dimple#58]
I have the following configuration for a bar graph, which should work based on the documentation for angular-dimple:

    <graph data="graphData" width="100%" height="100%">
	  <x field="date"></x>
      <y field="posts"></y>
      <bar field="sourceId" value="1"></bar>
      <bar field="sourceId" value="2"></bar>
    </graph>
 
 However, this renders as a stacked bar graph.  In fact, if I replace bar with area, the area graph also renders as a stacked area graph.

**Comment by paulcpederson** [comment]
Multiple bars will give you a stacked bar graph. A `bar` represents many drawn bars all in the same color. A bar will be drawn for each data entry. 

You can also "group" bars on the x axis as in the second example here: http://esripdx.github.io/angular-dimple/examples/#/bar

Does that make sense? Feel free to reopen if I didn't actually address your question, and sorry for the late reply!
