### ISSUE TITLE
Bind chart properties?

### ISSUE THREAD

**Issue by danielmcquillen** [esripdx/angular-dimple#60]
Is it possible to bind chart properties to the $scope if we're dynamically updating a chart based on user input?

e.g.
 ```<y field="y" type="Measure" title="{{ esChartYAxisLabel }}"></y>```

(Thanks for putting together this library. It's quite helpful.)

**Comment by ajkavanagh** [comment]
How come this was closed?  Does it work, and if so, on which version?  Thanks.
